apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: masterplan
spec:
  gateway: kyma-system/kyma-gateway
  host: masterplan.b5ade66.kyma.ondemand.com
  service:
    name: masterplan
    port: 80
  rules:
    - path: /.*
      methods: ["GET", "POST", "PUT", "DELETE"]
      mutators: []
      accessStrategies:
        - handler: oauth2_introspection
          config:
            required_scope: ["read"]

apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: 'masterplan'
  labels: {}
  annotations: {}
  namespace: masterplan
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: masterplan.b5ade66.kyma.ondemand.com
  service:
    name: masterplan
    port: 80
  rules:
    - path: /.*
      methods:
        - GET
      accessStrategies:
        - handler: allow
