version: "3.7"
services:
  app:
    build:
      args:
        user: hagar
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: masterplan
    container_name: masterplan-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - 8000:8000
    #volumes:
     # - ./:/var/www
    networks:
      - masterplan


  db:
    image: mysql:8.0
    container_name: masterplan-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - masterplan
    ports:
      - 3306:3306

#  nginx:
#    image: nginx:alpine
#    container_name: masterplan-nginx
#    restart: unless-stopped
#    ports:
#      - 80:80
#    volumes:
#      - ./:/var/www
#      - ./docker-compose/nginx:/etc/nginx/conf.d/
#    networks:
#      - masterplan

networks:
  masterplan:
    driver: bridge
